SELECT count(*) FROM sample_311 WHERE "landmark"='LINDEN BOULEVARD';
SELECT count(*) FROM sample_311 WHERE "complain_type"='Noise - Street/Sidewalk';
SELECT count(*) FROM sample_311 WHERE "community_board"='02 BROOKLYN';
SELECT count(*) FROM sample_311 WHERE "community_board"='80 QUEENS';
SELECT count(*) FROM sample_311 WHERE "city"='WHITESTONE';
SELECT count(*) FROM sample_311 WHERE "intersection_street_1"='EAST  110 STREET';
SELECT count(*) FROM sample_311 WHERE "community_board"='04 QUEENS';
SELECT count(*) FROM sample_311 WHERE "status"='In Progress';
SELECT count(*) FROM sample_311 WHERE "channel_type"='UNKNOWN';
SELECT count(*) FROM sample_311 WHERE "channel_type"='MOBILE';
SELECT count(*) FROM sample_311 WHERE "street_name"='AMETHYST STREET';
SELECT count(*) FROM sample_311 WHERE "descriptor_type"='Failure To Retain Water/Improper Drainage- (LL103/89)';
SELECT count(*) FROM sample_311 WHERE "street_name"='PEARSALL AVENUE';
SELECT count(*) FROM sample_311 WHERE "borough"='BRONX';
SELECT count(*) FROM sample_311 WHERE "agency_name"='Manhattan 05';
SELECT count(*) FROM sample_311 WHERE "agency"='DCA';
SELECT count(*) FROM sample_311 WHERE "street_name"='HOLLYWOOD AVENUE';
SELECT count(*) FROM sample_311 WHERE "status"='In Progress';
SELECT count(*) FROM sample_311 WHERE "intersection_street_2"='CUMMING STREET';
SELECT count(*) FROM sample_311 WHERE "cross_street_2"='EAST  103 STREET';
SELECT count(*) FROM sample_311 WHERE "city"='OZONE PARK' and "intersection_street_2"='EAST  161 STREET';
SELECT count(*) FROM sample_311 WHERE "complain_type"='Plumbing' and "address_type"='ADDRESS';
SELECT count(*) FROM sample_311 WHERE "borough"='MANHATTAN' and "city"='Little Neck';
SELECT count(*) FROM sample_311 WHERE "intersection_street_1"='WEST   30 STREET' and "descriptor_type"='MAILBOX';
SELECT count(*) FROM sample_311 WHERE "address_type"='BLOCKFACE' and "borough"='Unspecified';
SELECT count(*) FROM sample_311 WHERE "borough"='BROOKLYN' and "street_name"='PUTNAM AVENUE';
SELECT count(*) FROM sample_311 WHERE "community_board"='09 MANHATTAN' and "descriptor_type"='Blocked Hydrant';
SELECT count(*) FROM sample_311 WHERE "street_name"='69 PLACE' and "address_type"='INTERSECTION';
SELECT count(*) FROM sample_311 WHERE "community_board"='Unspecified MANHATTAN' and "agency"='HPD';
SELECT count(*) FROM sample_311 WHERE "agency_name"='Manhattan 03' and "intersection_street_2"='LA SALLE STREET';
SELECT count(*) FROM sample_311 WHERE "city"='BROOKLYN' and "street_name"='MANILA PLACE';
SELECT count(*) FROM sample_311 WHERE "cross_street_2"='E 34 ST' and "community_board"='08 MANHATTAN';
SELECT count(*) FROM sample_311 WHERE "location_type"='Construction Site' and "descriptor_type"='JANITOR/SUPER';
SELECT count(*) FROM sample_311 WHERE "community_board"='01 BRONX' and "descriptor_type"='Hyd Valve Box Cover Missing (WV2)';
SELECT count(*) FROM sample_311 WHERE "agency_name"='BCC - Bronx' and "cross_street_2"='171 STREET';
SELECT count(*) FROM sample_311 WHERE "city"='SOUTH RICHMOND HILL' and "complain_type"='Street Sign - Dangling';
SELECT count(*) FROM sample_311 WHERE "community_board"='12 MANHATTAN' and "intersection_street_1"='PACIFIC STREET';
SELECT count(*) FROM sample_311 WHERE "cross_street_2"='132 STREET' and "city"='Jamaica';
SELECT count(*) FROM sample_311 WHERE "city"='HOLLIS' and "cross_street_1"='222 ST';
SELECT count(*) FROM sample_311 WHERE "address_type"='ADDRESS' and "cross_street_1"='WEST  123 STREET';
SELECT count(*) FROM sample_311 WHERE "agency"='DOHMH' and "status"='Closed' and "community_board"='02 QUEENS';
SELECT count(*) FROM sample_311 WHERE "descriptor_type"='Rodents/Insects/Garbage' and "channel_type"='ONLINE' and "community_board"='14 QUEENS';
SELECT count(*) FROM sample_311 WHERE "descriptor_type"='Debris - Falling Or In Danger Of Falling' and "agency"='TLC' and "intersection_street_1"='HAMILTON AVENUE';
SELECT count(*) FROM sample_311 WHERE "location_type"='Construction Site' and "landmark"='MAC DONOUGH STREET' and "agency"='DOHMH';
SELECT count(*) FROM sample_311 WHERE "intersection_street_1"='CONTINENTAL AVENUE' and "landmark"='WOODHAVEN BOULEVARD' and "cross_street_1"='AVENUE R';
SELECT count(*) FROM sample_311 WHERE "status"='Assigned' and "community_board"='05 BROOKLYN' and "street_name"='ELLSWORTH AVENUE';
SELECT count(*) FROM sample_311 WHERE "borough"='BRONX' and "status"='In Progress' and "intersection_street_2"='EAST    2 STREET';
SELECT count(*) FROM sample_311 WHERE "agency"='DOT' and "agency_name"='Economic Development Corporation' and "community_board"='28 BRONX';
SELECT count(*) FROM sample_311 WHERE "complain_type"='Consumer Complaint' and "park_borough"='Unspecified' and "location_type"='Highway';
SELECT count(*) FROM sample_311 WHERE "complain_type"='Panhandling' and "address_type"='INTERSECTION' and "channel_type"='UNKNOWN';
SELECT count(*) FROM sample_311 WHERE "street_name"='NORTH HENRY STREET' and "cross_street_1"='HOOVER AVE' and "agency_name"='Bronx 05';
SELECT count(*) FROM sample_311 WHERE "descriptor_type"='Neglected' and "intersection_street_2"='WILLIAM STREET' and "agency"='DHS';
SELECT count(*) FROM sample_311 WHERE "community_board"='10 BROOKLYN' and "complain_type"='Sidewalk Condition' and "descriptor_type"='Highway Fence';
SELECT count(*) FROM sample_311 WHERE "intersection_street_2"='105 AVENUE' and "status"='In Progress' and "city"='EAST ELMHURST';
SELECT count(*) FROM sample_311 WHERE "agency_name"='BCC - Manhattan' and "address_type"='INTERSECTION' and "landmark"='140 STREET';
SELECT count(*) FROM sample_311 WHERE "agency_name"='Bronx 03' and "intersection_street_1"='LAFAYETTE AVENUE' and "street_name"='GRAHAM AVENUE';
SELECT count(*) FROM sample_311 WHERE "park_borough"='QUEENS' and "city"='Hollis' and "street_name"='219 STREET';
SELECT count(*) FROM sample_311 WHERE "descriptor_type"='Tree Leaning/Uprooted' and "agency_name"='Economic Development Corporation' and "borough"='STATEN ISLAND';
SELECT count(*) FROM sample_311 WHERE "agency"='HPD' and "park_borough"='STATEN ISLAND' and "location_type"='Street/Curbside';
SELECT count(*) FROM sample_311 WHERE "channel_type"='ONLINE' and "agency_name"='Bronx 03' and "location_type"='Club/Bar/Restaurant';
SELECT count(*) FROM sample_311 WHERE "agency_name"='New York City Police Department' and "status"='Closed' and "address_type"='ADDRESS' and "borough"='Unspecified';
SELECT count(*) FROM sample_311 WHERE "cross_street_1"='12 AVENUE' and "city"='Saint Albans' and "agency"='EDC' and "street_name"='EAST  117 STREET';
SELECT count(*) FROM sample_311 WHERE "street_name"='WEST END AVENUE' and "agency_name"='Department of Environmental Protection' and "location_type"='Stairwell' and "status"='Open';
SELECT count(*) FROM sample_311 WHERE "cross_street_1"='LEROY STREET' and "complain_type"='DOOR/WINDOW' and "intersection_street_2"='165 STREET' and "location_type"='3+ Family Apartment Building';
SELECT count(*) FROM sample_311 WHERE "city"='Fresh Meadows' and "location_type"='Parking Lot/Garage' and "intersection_street_2"='ELLINGTON STREET' and "agency"='DSNY';
SELECT count(*) FROM sample_311 WHERE "intersection_street_1"='57 STREET' and "borough"='BRONX' and "park_borough"='QUEENS' and "intersection_street_2"='WEST  176 STREET';
SELECT count(*) FROM sample_311 WHERE "landmark"='153 STREET' and "borough"='BRONX' and "cross_street_2"='258 STREET' and "location_type"='Parking Lot/Garage';
SELECT count(*) FROM sample_311 WHERE "park_borough"='BROOKLYN' and "address_type"='INTERSECTION' and "intersection_street_1"='EAST   95 STREET' and "status"='Pending';
SELECT count(*) FROM sample_311 WHERE "borough"='MANHATTAN' and "intersection_street_2"='MONTEREY AVENUE' and "address_type"='BLOCKFACE' and "street_name"='WEST  141 STREET';
SELECT count(*) FROM sample_311 WHERE "park_borough"='MANHATTAN' and "complain_type"='Home Delivered Meal - Missed Delivery' and "location_type"='Mobile Food Vendor' and "intersection_street_1"='74 PLACE';
SELECT count(*) FROM sample_311 WHERE "agency"='DOITT' and "cross_street_2"='WEST 187 STREET' and "park_borough"='QUEENS' and "status"='Assigned';
SELECT count(*) FROM sample_311 WHERE "cross_street_1"='WEST    4 STREET' and "descriptor_type"='Hydrant Running Full (WA4)' and "channel_type"='MOBILE' and "complain_type"='Illegal Parking';
SELECT count(*) FROM sample_311 WHERE "community_board"='01 MANHATTAN' and "agency"='DSNY' and "agency_name"='Brooklyn South 10' and "park_borough"='MANHATTAN';
SELECT count(*) FROM sample_311 WHERE "location_type"='Private School' and "status"='Pending' and "descriptor_type"='Failure To Maintain' and "park_borough"='STATEN ISLAND';
SELECT count(*) FROM sample_311 WHERE "intersection_street_2"='NORTH CONDUIT AVENUE' and "status"='Closed' and "community_board"='Unspecified BROOKLYN' and "channel_type"='MOBILE';
SELECT count(*) FROM sample_311 WHERE "agency_name"='A - Manhattan' and "landmark"='BODINE STREET' and "intersection_street_2"='PITKIN AVENUE' and "community_board"='01 BROOKLYN';
SELECT count(*) FROM sample_311 WHERE "agency"='DOHMH' and "park_borough"='BROOKLYN' and "cross_street_2"='20 DRIVE' and "status"='Open';
SELECT count(*) FROM sample_311 WHERE "intersection_street_1"='ADEE AVENUE' and "cross_street_2"='150 AVENUE' and "city"='FOREST HILLS' and "borough"='BRONX';
SELECT count(*) FROM sample_311 WHERE "borough"='BRONX' and "address_type"='ADDRESS' and "agency_name"='Bronx 11' and "location_type"='Parking Lot/Garage';
SELECT count(*) FROM sample_311 WHERE "address_type"='INTERSECTION' and "cross_street_1"='CALYER STREET' and "community_board"='80 QUEENS' and "location_type"='Public/Unfenced Area';
SELECT count(*) FROM sample_311 WHERE "cross_street_2"='QUINTARD STREET' and "descriptor_type"='Fixture/Luminaire Door Open' and "address_type"='ADDRESS' and "street_name"='18 AVENUE' and "location_type"='RESIDENTIAL BUILDING';
SELECT count(*) FROM sample_311 WHERE "status"='Pending' and "intersection_street_1"='EAST   57 STREET' and "borough"='BRONX' and "channel_type"='UNKNOWN' and "street_name"='WHITEPLAINS ROAD';
SELECT count(*) FROM sample_311 WHERE "complain_type"='Derelict Vehicles' and "cross_street_1"='EAST    9 STREET' and "channel_type"='MOBILE' and "intersection_street_2"='KNICKERBOCKER AVENUE' and "status"='Open';
SELECT count(*) FROM sample_311 WHERE "community_board"='09 QUEENS' and "cross_street_1"='GREYSTONE AVENUE' and "complain_type"='Building/Use' and "borough"='BROOKLYN' and "street_name"='149 PLACE';
SELECT count(*) FROM sample_311 WHERE "descriptor_type"='Table Not in Compliance' and "cross_street_1"='RUTGERS SLIP' and "agency_name"='New York City Police Department' and "address_type"='INTERSECTION' and "community_board"='12 MANHATTAN';
SELECT count(*) FROM sample_311 WHERE "descriptor_type"='Inadequate or No Heat' and "location_type"='Park/Playground' and "complain_type"='Air Quality' and "status"='Pending' and "landmark"='FT HAMILTON PARKWAY';
SELECT count(*) FROM sample_311 WHERE "channel_type"='ONLINE' and "intersection_street_1"='SUTPHIN BOULEVARD' and "cross_street_1"='112 STREET' and "community_board"='13 BROOKLYN' and "address_type"='INTERSECTION';
SELECT count(*) FROM sample_311 WHERE "address_type"='INTERSECTION' and "location_type"='Parking Lot/Garage' and "intersection_street_2"='KNEELAND AVENUE' and "agency_name"='New York City Police Department' and "city"='Far Rockaway';
SELECT count(*) FROM sample_311 WHERE "park_borough"='MANHATTAN' and "status"='Assigned' and "landmark"='45 AVENUE' and "complain_type"='HEAT/HOT WATER' and "city"='Kew Gardens';
SELECT count(*) FROM sample_311 WHERE "intersection_street_1"='67 STREET' and "address_type"='BLOCKFACE' and "channel_type"='MOBILE' and "landmark"='TUDOR CITY PLACE' and "borough"='STATEN ISLAND';
SELECT count(*) FROM sample_311 WHERE "city"='Whitestone' and "complain_type"='PAINT/PLASTER' and "descriptor_type"='Tax Preparer' and "landmark"='EAST   53 PLACE' and "address_type"='INTERSECTION';
SELECT count(*) FROM sample_311 WHERE "agency_name"='Queens East 12' and "cross_street_1"='WEST 133 STREET' and "city"='Rosedale' and "park_borough"='BRONX' and "descriptor_type"='Culvert Blocked/Needs Cleaning (SE)';
SELECT count(*) FROM sample_311 WHERE "cross_street_2"='DEVENS STREET' and "park_borough"='Unspecified' and "landmark"='32 STREET' and "complain_type"='Graffiti' and "intersection_street_2"='103 AVENUE';
SELECT count(*) FROM sample_311 WHERE "community_board"='11 BRONX' and "cross_street_2"='PARSONS BOULEVARD' and "complain_type"='Food Poisoning' and "location_type"='Sidewalk' and "descriptor_type"='Street Light Out';
SELECT count(*) FROM sample_311 WHERE "agency"='DOB' and "intersection_street_1"='2 AVENUE' and "intersection_street_2"='EAST  161 STREET' and "agency_name"='Department of Buildings' and "complain_type"='For Hire Vehicle Complaint';
SELECT count(*) FROM sample_311 WHERE "channel_type"='PHONE' and "city"='ARVERNE' and "community_board"='03 BROOKLYN' and "agency"='DFTA' and "intersection_street_1"='PITKIN AVENUE';
SELECT count(*) FROM sample_311 WHERE "location_type"='Taxi' and "agency_name"='Bronx 03' and "borough"='Unspecified' and "agency"='DOB' and "landmark"='EAST   48 STREET';
SELECT count(*) FROM sample_311 WHERE "borough"='QUEENS' and "agency_name"='Department of Information Technology and Telecommunications' and "channel_type"='UNKNOWN' and "status"='Assigned' and "park_borough"='BRONX';
SELECT count(*) FROM sample_311 WHERE "landmark"='WEST   28 STREET' and "status"='In Progress' and "descriptor_type"='Electronics/Phones' and "address_type"='INTERSECTION' and "channel_type"='UNKNOWN';
SELECT count(*) FROM sample_311 WHERE "agency_name"='Department of Information Technology and Telecommunications' and "channel_type"='ONLINE' and "cross_street_1"='109 AVENUE' and "city"='ASTORIA' and "street_name"='PROSPECT PARK WEST';
